<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Taiga.Core\Taiga.Core.csproj" />
    <ProjectReference Include="..\Taiga.Sync\Taiga.Sync.csproj" />
    <ProjectReference Include="..\Taiga.Track\Taiga.Track.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>All</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Taiga.Server.Tests" />
  </ItemGroup>

</Project>
